### ISSUE TITLE
DecimalRow validation rules affect text input formatting

### ISSUE THREAD

**Issue by sgerardi** [xmartlabs/Eureka#909]
Version: 2.0.0-beta.1

Entering the first character into an empty `DecimalRow` with one or more validation rules triggers a cell upate causing the text to include an unexpected trailing decimal ".0". In order to enter a larger number, the user must delete the trailing characters (".0") first.

If the the row does not contain any validation rules, the input works as expected: Entering a single digit into an empty field does not append the trailing decimal to the text.

#### Example:

Given the following decimal row:

```swift
section <<< DecimalRow() {
    $0.title = "Number"
    $0.add(rule: RuleGreaterThan(min: 0))
}
```

1. Tap the cell to become the active text input field.
2. Type a single digit, such as "1"

Notice the text immediately changes to "1.0" and moves the caret to the end of the field.  In order to enter the text "12.34", the user must first delete the ".0".

#### Proposed Resolution:

The existing implementation of the `value` property calls `updateCell()` immedaitely after calling `validate()`.  The simplest solution would be to remove the call to `updateCell()`.

```swift
// Row.swift

open var value : T?{
    set (newValue){
        _value = newValue
        guard let _ = section?.form else { return }
        wasChanged = true
        if validationOptions.contains(.validatesOnChange) || (wasBlurred && validationOptions.contains(.validatesOnChangeAfterBlurred)) || !isValid   {
            validate()
            updateCell()
        }
    }
    get {
        return _value
    }
}
```

**Comment by mtnbarreto** [comment]
@sgerardi  which Eureka version are you using?

**Comment by sgerardi** [comment]
Version 2.0.0-beta.1

**Comment by mtnbarreto** [comment]
@sgerardi Could you check if master branch version works, seems to me is already fixed.

**Comment by sgerardi** [comment]
It appears to be fixed in the master branch.  I've been using version 2.0.0-beta1 because I need Swift 3 compatibility.  Installing Eureka with `pod 'Eureka'`installs version 1.7.0 which doesn't support Swift 3.  Should I just target the master branch instead of the specific version?

pod 'Eureka', :git => 'hhttps://github.com/xmartlabs/Eureka.git', :branch => 'master'

**Comment by mtnbarreto** [comment]
you should target the master branch as you said.

**Comment by Mutix** [comment]
FWIW, I'm still seeing this issue even when targeting master

**Comment by luizv** [comment]
Still seeing this issue in 4.0.0. Any turnarounds?
